<?php
namespace Database\Seeders;
use App\Models\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;
use App\Models\Permission;
use App\Models\Role;

class UserSeeder extends Seeder
{
    public function run()
    {
        //permission
         $permissions = [
            ['slug' => 'Finance-Administration-Modules', 'name' => 'View Finance And Administration Modules Menus'],
            ['slug' => 'Administration-Modules', 'name' => 'View Administration Modules Menus'],
            ['slug' => 'Access-All-Companies-Data', 'name' => 'Access All Companies Data'],
            ['slug' => 'Access-All-Units-Data', 'name' => 'Access All Units Data'],
            ['slug' => 'Access-All-WorkPoints-Data', 'name' => 'Access All Work Points Data'],
            ['slug' => 'View-Company&Work-Point-Menu', 'name' => 'View Company & Work Point Menu'],
            ['slug' => 'View-Company-Site', 'name' => 'View Company Site Details'],
            ['slug' => 'Register-Company-Site', 'name' => 'Register Company Site Details'],
            ['slug' => 'Edit-Company-Site', 'name' => 'Edit Company Site Details'],
            ['slug' => 'Delete-Company-Site', 'name' => 'Delete Company Site Details'],
            ['slug' => 'View-Company-Unit', 'name' => 'View Company Unit Details'],
            ['slug' => 'Register-Company-Unit', 'name' => 'Register Company Unit Details'],
            ['slug' => 'Edit-Company-Unit', 'name' => 'Edit Company Unit Details'],
            ['slug' => 'Delete-Company-Unit', 'name' => 'Delete Company Unit Details'],
            ['slug' => 'View-Location', 'name' => 'View Location Details'],
            ['slug' => 'Register-workpoint', 'name' => 'Register Location Details'],
            ['slug' => 'Edit-Location', 'name' => 'Edit Location Details'],
            ['slug' => 'Delete-Location', 'name' => 'Delete Location Details'],
            ['slug' => 'View-Department', 'name' => 'View Department Details'],
            ['slug' => 'Register-Department', 'name' => 'Register Department Details'],
            ['slug' => 'Edit-Department', 'name' => 'Edit Department Details'],
            ['slug' => 'Delete-Department', 'name' => 'Delete Department Details'],
            ['slug' => 'View-Section', 'name' => 'View Section Details'],
            ['slug' => 'Register-Section', 'name' => 'Register Section Details'],
            ['slug' => 'Edit-Section', 'name' => 'Edit Section Details'],
            ['slug' => 'Delete-Section', 'name' => 'Delete Section Details'],
            ['slug' => 'View-Title/Role-Details', 'name' => 'View Title/Role Details'],
            ['slug' => 'Register-Title/Role-Details', 'name' => 'Register Title/Role Details'],
            ['slug' => 'Delete-Title/Role-Details', 'name' => 'Delete Title/Role Details'],
            ['slug' => 'HR-Modules', 'name' => 'View Human Resources Modules'],
            ['slug' => 'View-Staff-Details-Menu', 'name' => 'View Staff Details Menu'],
            ['slug' => 'View-Staff', 'name' => 'View Staff Details'],
            ['slug' => 'Register-Staff', 'name' => 'Register Staff Details'],
            ['slug' => 'Edit-Staff', 'name' => 'Edit-Staff Details'],
            ['slug' => 'View-NextOfKin', 'name' => 'View Next of Kin'],
            ['slug' => 'Register-NextOfKin', 'name' => 'Register Next of Kin'],
            ['slug' => 'Edit-NextOfKin', 'name' => 'Edit Next of Kin'],
            ['slug' => 'Delete-NextOfKin', 'name' => 'Delete Next of Kin'],
            ['slug' => 'View-Education', 'name' => 'View Staff Education Details'],
            ['slug' => 'Register-Education', 'name' => 'Register Staff Education Details'],
            ['slug' => 'Edit-Education', 'name' => 'Edit Staff Education Details'],
            ['slug' => 'Delete-Education', 'name' => 'Delete Staff Education Details'],
            ['slug' => 'View-Staff-Documents', 'name' => 'View Staff Documents'],
            ['slug' => 'Register-Staff-Documents', 'name' => 'Register Staff Documents'],
            ['slug' => 'Edit-Staff-Documents', 'name' => 'Edit Staff Documents'],
            ['slug' => 'Delete-Staff-Documents', 'name' => 'Delete Staff Documents'],
            ['slug' => 'View-HR-Menu', 'name' => 'View HR Menu'],
            ['slug' => 'View-Leaves', 'name' => 'View Leaves'],
            ['slug' => 'Register-Leave', 'name' => 'Register Leave'],
            ['slug' => 'Edit-Leave', 'name' => 'Edit Leave'],
            ['slug' => 'Delete-Leave', 'name' => 'Delete Leave'],
            ['slug' => 'Approve-Leave', 'name' => 'Approve Leave'],
            ['slug' => 'View-Loans', 'name' => 'View Loans & Advances'],
            ['slug' => 'Register-Loan', 'name' => 'Register Loan/Advance'],
            ['slug' => 'Edit-Loan', 'name' => 'Edit Loan/Advance'],
            ['slug' => 'Delete-Loan', 'name' => 'Delete Loan/Advance'],
            ['slug' => 'View-Payroll-Menu', 'name' => 'View Payroll Menu'],
            ['slug' => 'View-Payrolls', 'name' => 'View Payrolls'],
            ['slug' => 'Register-Payroll', 'name' => 'Prepare Payroll'],
            ['slug' => 'Edit-Payroll', 'name' => 'Edit Payroll'],
            ['slug' => 'Approve-Payroll', 'name' => 'Approve Payroll'],
            ['slug' => 'Pay-Payroll', 'name' => 'Pay Payroll'],
            ['slug' => 'Delete-Payroll', 'name' => 'Cancel Payroll'],
            ['slug' => 'View-Payroll-Reports', 'name' => 'View Payroll Reports'],
            ['slug' => 'Print-Payroll-Sheets', 'name' => 'Print Payroll Sheets'],
            ['slug' => 'View-Payslip', 'name' => 'View Payslip'],
            ['slug' => 'Print-Payslip', 'name' => 'Print Payslip'],
            ['slug' => 'View-Overtimes', 'name' => 'View Overtimes'],
            ['slug' => 'Register-Overtime', 'name' => 'Register Overtime'],
            ['slug' => 'Edit-Overtime', 'name' => 'Edit Overtime'],
            ['slug' => 'Approve-Overtime', 'name' => 'Approve Overtime'],
            ['slug' => 'Pay-Overtime', 'name' => 'Pay Overtime'],
            ['slug' => 'Delete-Overtime', 'name' => 'Delete Overtime'],
            ['slug' => 'View-Absences', 'name' => 'View Absences'],
            ['slug' => 'Register-Absence', 'name' => 'Register Absence'],
            ['slug' => 'Edit-Absence', 'name' => 'Edit Absence'],
            ['slug' => 'Approve-Absence', 'name' => 'Approve Absence'],
            ['slug' => 'Delete-Absence', 'name' => 'Delete Absence'],
            ['slug' => 'Accounting-Modules', 'name' => 'View Accounting Modules'],
            ['slug' => 'View-Accounting-Code-Menu', 'name' => 'View Accounting Code Menu'],
            ['slug' => 'View-Accounting-Code', 'name' => 'View Accounting Code'],
            ['slug' => 'Register-Accounting-Code', 'name' => 'Register Accounting Code'],
            ['slug' => 'Edit-Accounting-Code', 'name' => 'Edit Accounting Code'],
            ['slug' => 'Delete-Accounting-Code', 'name' => 'Delete Accounting Code'],
            ['slug' => 'View-Sub-Accounting-Code', 'name' => 'View Sub Accounting Code'],
            ['slug' => 'Register-Sub-Accounting-Code', 'name' => 'Register Sub Accounting Code'],
            ['slug' => 'Edit-Sub-Accounting-Code', 'name' => 'Edit Sub Accounting Code'],
            ['slug' => 'Delete-Sub-Accounting-Code', 'name' => 'Delete Sub Accounting Code'],
            ['slug' => 'View-Accounting-Transaction-Menu', 'name' => 'View Accounting Transaction Menu'],
            ['slug' => 'View-All-Accounting-Transactions', 'name' => 'View All Accounting Transactions'],
            ['slug' => 'View-Company-Accounting-Transactions', 'name' => 'View Company Accounting Transactions'],
            ['slug' => 'View-Unit-Accounting-Transactions', 'name' => 'View Unit Accounting Transactions'],
            ['slug' => 'View-Accounting-Transactions', 'name' => 'View Accounting Transactions'],
            ['slug' => 'Register-Accounting-Transactions', 'name' => 'Register Accounting Transactions'],
            ['slug' => 'Edit-Accounting-Transactions', 'name' => 'Edit Accounting Transactions'],
            ['slug' => 'Delete-Accounting-Transactions', 'name' => 'Delete Accounting Transactions'],
            ['slug' => 'Verify-Accounting-Transactions', 'name' => 'Verify Accounting Transactions'],
            ['slug' => 'Approve-Accounting-Transactions', 'name' => 'Approve Accounting Transactions'],
            ['slug' => 'Import-Accounting-Transactions', 'name' => 'Import Accounting Transactions'],
            ['slug' => 'View-Accounting-Reports', 'name' => 'View-Accounting-Reports'],
            ['slug' => 'View-Ledger-Details-Report', 'name' => 'View Ledger Details Report'],
            ['slug' => 'View-Trial-Balance-Report', 'name' => 'View Trial Balance Report'],
            ['slug' => 'View-Monthly-Trial-Balance-Report', 'name' => 'View Monthly Trial Balance Report'],
            ['slug' => 'View-Profit-&-Loss-Report', 'name' => 'View Profit & Loss Report'],
            ['slug' => 'View-Balance-Sheet-Report', 'name' => 'View Balance Sheet Report'],
            ['slug' => 'View-Change-in-Equity-Report', 'name' => 'View Change in Equity Report'],
            ['slug' => 'View-Cash-Flow-Report', 'name' => 'View Cash Flow Report'],
            ['slug' => 'View-Asset-Menu', 'name' => 'View Asset Menu'],
            ['slug' => 'View-Asset-Categories', 'name' => 'View Asset Categories'],
            ['slug' => 'Register-Asset-Categories', 'name' => 'Register Asset Categories'],
            ['slug' => 'Edit-Asset-Categories', 'name' => 'Edit Asset Categories'],
            ['slug' => 'Delete-Asset-Categories', 'name' => 'Delete Asset Categories'],
            ['slug' => 'View-Asset-Transactions', 'name' => 'View Asset Transactions'],
            ['slug' => 'Register-Asset-Transactions', 'name' => 'Register Asset Transactions'],
            ['slug' => 'Edit-Asset-Transactions', 'name' => 'Edit Asset Transactions'],
            ['slug' => 'Delete-Asset-Transactions', 'name' => 'Delete Asset Transactions'],
            ['slug' => 'Dispose-Asset', 'name' => 'Dispose Asset'],
            ['slug' => 'Revalue-Asset', 'name' => 'Revalue Asset'],
            ['slug' => 'View-Asset-Report', 'name' => 'View Asset Report'],
            ['slug' => 'View-Insurance-Menu', 'name' => 'View Insurance Menu'],
            ['slug' => 'View-ICT-Menu', 'name' => 'View ICT Menu'],
            ['slug' => 'View-ICT-Issues-Menu', 'name' => 'View ICT Issues Menu'],
            ['slug' => 'View-Software-Hardware-Issues', 'name' => 'View Software and Hardware Issues'],
            ['slug' => 'Register-Software-Hardware-Issues', 'name' => 'Register Software and Hardware Issues'],
            ['slug' => 'Edit-Software-Hardware-Issues', 'name' => 'Edit Software and Hardware Issues'],
            ['slug' => 'Delete-Software-Hardware-Issues', 'name' => 'Delete Software and Hardware Issues'],
            ['slug' => 'Assign-Software-Hardware-Issue', 'name' => 'Assign Software and Hardware Issue'],
            ['slug' => 'Resolve-Software-Hardware-Issue', 'name' => 'Resolve Software and Hardware Issue'],
            ['slug' => 'View-ICT-Maintenance-Menu', 'name' => 'View ICT Maintenance Menu'],
            ['slug' => 'View-IT-Maintenance', 'name' => 'View IT Maintenance'],
            ['slug' => 'Register-IT-Maintenance', 'name' => 'Register IT Maintenance'],
            ['slug' => 'Edit-IT-Maintenance', 'name' => 'Edit IT Maintenance'],
            ['slug' => 'Delete-IT-Maintenance', 'name' => 'Delete IT Maintenance'],
            ['slug' => 'Approve-IT-Maintenance', 'name' => 'Approve IT Maintenance'],
            ['slug' => 'Complete-IT-Maintenance', 'name' => 'Complete IT Maintenance'],
            ['slug' => 'View-Internal-Audit-Menu', 'name' => 'View Internal Audit Menu'],
            ['slug' => 'View-News', 'name' => 'View News'],
            ['slug' => 'Register-News', 'name' => 'Register News'],
            ['slug' => 'Edit-News', 'name' => 'Edit News'],
            ['slug' => 'Delete-News', 'name' => 'Delete News'],
            ['slug' => 'Production-Inventory-Manufacturing-Modules', 'name' => 'View Production, Invetory and Manufacturing Modules'],
            ['slug' => 'Inventory-Manufacturing-Modules', 'name' => 'View Invetory Manufacturing Modules'],
            ['slug' => 'View-Manufacturing-Raw-Material-Request', 'name' => 'View Manufacturing Raw Material Request'],
            ['slug' => 'Register-Manufacturing-Raw-Material-Request', 'name' => 'Register Manufacturing Raw Material Request'],
            ['slug' => 'Edit-Manufacturing-Raw-Material-Request', 'name' => 'Edit Manufacturing Raw Material Request'],
            ['slug' => 'Delete-Manufacturing-Raw-Material-Request', 'name' => 'Delete Manufacturing Raw Material Request'],
            ['slug' => 'View-Manufacturing-Receipts', 'name' => 'View Manufacturing Receipts'],
            ['slug' => 'Register-Manufacturing-Receipts', 'name' => 'Register Manufacturing Receipts'],
            ['slug' => 'Edit-Manufacturing-Receipts', 'name' => 'Edit Manufacturing Receipts'],
            ['slug' => 'Delete-Manufacturing-Receipts', 'name' => 'Delete Manufacturing Receipts'],
            ['slug' => 'View-Manufacturing-Stock', 'name' => 'View Manufacturing Stock'],
            ['slug' => 'View-Manufacturing-Stock-Movement', 'name' => 'View Manufacturing Stock Movement'],
            ['slug' => 'View-Manufacturing-Consumption', 'name' => 'View Manufacturing Consumption'],
            ['slug' => 'Register-Manufacturing-Consumption', 'name' => 'Register Manufacturing Consumption'],
            ['slug' => 'Edit-Manufacturing-Consumption', 'name' => 'Edit Manufacturing Consumption'],
            ['slug' => 'Delete-Manufacturing-Consumption', 'name' => 'Delete Manufacturing Consumption'],
            ['slug' => 'View-Manufacturing-Raw-Material-Menu', 'name' => 'View Manufacturing Raw Material Menu'],
            ['slug' => 'View-Manufacturing-Inventory-Menu', 'name' => 'View Manufacturing Inventory Menu'],
            ['slug' => 'View-Drilling-Blasting-Menu', 'name' => 'View Drilling & Blasting Menu'],
            ['slug' => 'View-Water-Supply-Menu', 'name' => 'View Water Supply Menu'],
            ['slug' => 'View-Construction-Menu', 'name' => 'View Construction Menu'],
            ['slug' => 'View-Innovation-Menu', 'name' => 'View Innovation Menu'],
            ['slug' => 'View-Raw-Material-Menu', 'name' => 'View Raw Material Menu'],
            ['slug' => 'View-Raw-Material', 'name' => 'View Raw Material Details'],
            ['slug' => 'Register-Raw-Material', 'name' => 'Register Raw Material Details'],
            ['slug' => 'Edit-Raw-Material', 'name' => 'Edit Raw Material Details'],
            ['slug' => 'Delete-Raw-Material', 'name' => 'Delete Raw Material Details'],
            ['slug' => 'View-Raw-Material-Price', 'name' => 'View Raw Material Price Details'],
            ['slug' => 'Register-Raw-Material-Price', 'name' => 'Register Raw Material Price Details'],
            ['slug' => 'Edit-Raw-Material-Price', 'name' => 'Edit Raw Material Price Details'],
            ['slug' => 'Delete-Raw-Material-Price', 'name' => 'Delete Raw Material Price Details'],
            ['slug' => 'View-Product-Menu', 'name' => 'View Product Menu'],
            ['slug' => 'View-Product', 'name' => 'View Product Details'],
            ['slug' => 'Register-Product', 'name' => 'Register Product Details'],
            ['slug' => 'Edit-Product', 'name' => 'Edit Product Details'],
            ['slug' => 'Delete-Product', 'name' => 'Delete Product Details'],
            ['slug' => 'View-Product-Price', 'name' => 'View Product Price Details'],
            ['slug' => 'Register-Product-Price', 'name' => 'Register Product Price Details'],
            ['slug' => 'Edit-Product-Price', 'name' => 'Edit Product Price Details'],
            ['slug' => 'Delete-Product-Price', 'name' => 'Delete Product Price Details'],
            ['slug' => 'View-Product-Inventory-Menu', 'name' => 'View Product Inventory Menu'],
            ['slug' => 'View-Packed-Product', 'name' => 'View Packed Products'],
            ['slug' => 'Register-Packed-Product', 'name' => 'Register Packed Product'],
            ['slug' => 'Edit-Packed-Product', 'name' => 'Edit Packed Product'],
            ['slug' => 'Delete-Packed-Product', 'name' => 'Delete Packed Product'],
            ['slug' => 'View-Product-Stock', 'name' => 'View Product Stock'],
            ['slug' => 'View-Product-Order', 'name' => 'View Product Orders'],
            ['slug' => 'Register-Product-Order', 'name' => 'Register Product Order'],
            ['slug' => 'Edit-Product-Order', 'name' => 'Edit Product Order'],
            ['slug' => 'Delete-Product-Order', 'name' => 'Delete Product Order'],
            ['slug' => 'View-Issued-Product', 'name' => 'View Issued Products'],
            ['slug' => 'Register-Issued-Product', 'name' => 'Register Issued Product'],
            ['slug' => 'Edit-Issued-Product', 'name' => 'Edit Issued Product'],
            ['slug' => 'Delete-Issued-Product', 'name' => 'Delete Issued Product'],
            ['slug' => 'View-Product-Stock-Movement', 'name' => 'View Product Stock Movement'],
            ['slug' => 'View-Stock-Management', 'name' => 'View Stock Management'],
            ['slug' => 'View-Stock-Dashboard', 'name' => 'View Stock Dashboard'],
            ['slug' => 'View-Stock-Modules', 'name' => 'View Stock Modules'],
            ['slug' => 'Create-Stock-In', 'name' => 'Create Stock In'],
            ['slug' => 'Create-Stock-Out', 'name' => 'Create Stock Out'],
            ['slug' => 'Create-Stock-Data', 'name' => 'Create Stock Data'],
            ['slug' => 'Edit-Stock-Data', 'name' => 'Edit Stock Data'],
            ['slug' => 'Delete-Stock-Data', 'name' => 'Delete Stock Data'],
            ['slug' => 'View-Stock-Ledger', 'name' => 'View Stock Ledger'],
            ['slug' => 'Export-Stock-Ledger', 'name' => 'Export Stock Ledger'],
            ['slug' => 'View-Stock-Reports', 'name' => 'View Stock Reports'],
            ['slug' => 'Export-Stock-Reports', 'name' => 'Export Stock Reports'],
            ['slug' => 'Print-Stock-Reports', 'name' => 'Print Stock Reports'],
            ['slug' => 'View-Stock-Audit', 'name' => 'View Stock Audit'],
            ['slug' => 'Create-Stock-Audit', 'name' => 'Create Stock Audit'],
            ['slug' => 'Edit-Stock-Audit', 'name' => 'Edit Stock Audit'],
            ['slug' => 'Delete-Stock-Audit', 'name' => 'Delete Stock Audit'],
            ['slug' => 'Approve-Stock-Audit', 'name' => 'Approve Stock Audit'],
            ['slug' => 'View-Stock-Alerts', 'name' => 'View Stock Alerts'],
            ['slug' => 'CRM-Modules', 'name' => 'View CRM Modules'],
            ['slug' => 'View-CustomerSupplier-Menu', 'name' => 'View Customer/Supplier Menu'],
            ['slug' => 'View-CustomerSupplier', 'name' => 'View Customers & Suppliers'],
            ['slug' => 'Register-CustomerSupplier', 'name' => 'Register Customers & Suppliers'],
            ['slug' => 'Edit-CustomerSupplier', 'name' => 'Edit Customers & Suppliers'],
            ['slug' => 'Delete-CustomerSupplier', 'name' => 'Delete Customers & Suppliers'],
            ['slug' => 'View-Customer-Orders', 'name' => 'View Customers & Suppliers Orders'],
            ['slug' => 'Register-Customer-Orders', 'name' => 'Register Customers & Suppliers Orders'],
            ['slug' => 'Edit-Customer-Orders', 'name' => 'Edit Customers & Suppliers Orders'],
            ['slug' => 'Delete-Customer-Orders', 'name' => 'Delete Customers & Suppliers Orders'],
            ['slug' => 'View-Customer-OrderItems', 'name' => 'View Customers & Suppliers Order Items'],
            ['slug' => 'Register-Customer-OrderItems', 'name' => 'Register Customers & Suppliers Order Items'],
            ['slug' => 'Edit-Customer-OrderItems', 'name' => 'Edit Customers & Suppliers Order Items'],
            ['slug' => 'Delete-Customer-OrderItems', 'name' => 'Delete Customers & Suppliers Order Items'],
            ['slug' => 'View-Customer-Ledger', 'name' => 'View Customers & Suppliers Ledger'],
            ['slug' => 'Register-Customer-Ledger', 'name' => 'Register Customers & Suppliers Ledger'],
            ['slug' => 'Edit-Customer-Ledger', 'name' => 'Edit Customers & Suppliers Ledger'],
            ['slug' => 'Delete-Customer-Ledger', 'name' => 'Delete Customers & Suppliers Ledger'],
            ['slug' => 'View-CustomerSupplier-Reports', 'name' => 'View Customer & Suppliers Reports'],
            ['slug' => 'View-Hired-Equipment-Menu', 'name' => 'View Hired Equipment Menu'],
            ['slug' => 'View-Hired-Equipment-Details', 'name' => 'View Hired Equipment Details'],
            ['slug' => 'Register-Hired-Equipment', 'name' => 'Register Hired Equipment Details'],
            ['slug' => 'Edit-Hired-Equipment', 'name' => 'Edit Hired Equipment Details'],
            ['slug' => 'Delete-Hired-Equipment', 'name' => 'Delete Hired Equipment Details'],
            ['slug' => 'View-Hired-Equipment-Workings', 'name' => 'View Hired Equipment Workings Details'],
            ['slug' => 'Register-Hired-Equipment-Working', 'name' => 'Register Hired Equipment Working Details'],
            ['slug' => 'Edit-Hired-Equipment-Working', 'name' => 'Edit Hired Equipment Working Details'],
            ['slug' => 'Delete-Hired-Equipment-Working', 'name' => 'Delete Hired Equipment Working Details'],
            ['slug' => 'Change-Hired-Equipment-PaymentStatus', 'name' => 'Change Hired Equipment Payment Status'],
            ['slug' => 'View-Hired-Equipment-Reports', 'name' => 'View Hired Equipment Reports'],
            ['slug' => 'Export-Hired-Equipment-Reports', 'name' => 'Export Hired Equipment Reports'],
            ['slug' => 'Business-Development-Sales-Marketing-Modules', 'name' => 'View Business Development, Sales & Marketing Modules'],
            ['slug' => 'Sales-Marketing-Modules', 'name' => 'View Sales & Marketing Modules'],
            ['slug' => 'View-General-Supply-Menu', 'name' => 'View General Supply Menu'],
            ['slug' => 'View-Store-Items-Menu', 'name' => 'View Store Items Menu'],
            ['slug' => 'View-Item-Details', 'name' => 'View Item Details'],
            ['slug' => 'Register-Item-Details', 'name' => 'Register Item Details'],
            ['slug' => 'Edit-Item-Details', 'name' => 'Edit Item Details'],
            ['slug' => 'Delete-Item-Details', 'name' => 'Delete Item Details'],
            ['slug' => 'View-Item-Description-Details', 'name' => 'View Item Description Details'],
            ['slug' => 'Register-Item-Description-Details', 'name' => 'Register Item Description Details'],
            ['slug' => 'Edit-Item-Description-Details', 'name' => 'Edit Item Description Details'],
            ['slug' => 'Delete-Item-Description-Details', 'name' => 'Delete Item Description Details'],
            ['slug' => 'View-Received-Item-Details', 'name' => 'View Received Item Details'],
            ['slug' => 'Register-Received-Item-Details', 'name' => 'Register Received Item Details'],
            ['slug' => 'Edit-Received-Item-Details', 'name' => 'Edit Received Item Details'],
            ['slug' => 'View-Requested-Items-Details', 'name' => 'View Requested Items Details'],
            ['slug' => 'Register-Requested-Items-Details', 'name' => 'Register Requested Items Details'],
            ['slug' => 'Edit-Requested-Items-Details', 'name' => 'Edit Requested Items Details'],
            ['slug' => 'Delete-Requested-Items-Details', 'name' => 'Delete Requested Items Details'],
            ['slug' => 'View-Issued-Items-Details', 'name' => 'View Issued Items Details'],
            ['slug' => 'Issue-Requested-Items', 'name' => 'Issue Requested Items'],
            ['slug' => 'View-Items-Stock-Details', 'name' => 'View Items Stock Details'],
            ['slug' => 'View-Purchase-Report', 'name' => 'View Purchase Report'],
            ['slug' => 'View-Requisition-Report', 'name' => 'View Requisition Report'],
            ['slug' => 'Confirm-Received-Requested-Items', 'name' => 'Confirm Received Requested Items'],
            ['slug' => 'View-All-General-Supply-Requests', 'name' => 'View All General Supply Requests'],
            ['slug' => 'View-Company-General-Supply-Requests', 'name' => 'View Company General Supply Requests'],
            ['slug' => 'View-Unit-General-Supply-Requests', 'name' => 'View Unit General Supply Requests'],
            ['slug' => 'View-General-Supply-All', 'name' => 'View General Supply All'],
            ['slug' => 'View-General-Supply-Company', 'name' => 'View General Supply Company'],
            ['slug' => 'View-General-Supply-Unit', 'name' => 'View General Supply Unit'],
            ['slug' => 'View-Logistics-Menu', 'name' => 'View Logistics Menu'],
            ['slug' => 'View-Store-Management-Menu', 'name' => 'View Store Management Menu'],
            ['slug' => 'View-Procurement-Raw-Materials-Menu', 'name' => 'View Procurement Raw Materials Menu'],
            ['slug' => 'View-Vendor-Management-Menu', 'name' => 'View Vendor Management Menu'],
            ['slug' => 'View-Purchase-Orders-Contracts-Menu', 'name' => 'View Purchase Orders Contracts Menu'],
            ['slug' => 'View-Inventory-Control-Menu', 'name' => 'View Inventory Control Menu'],
            ['slug' => 'View-Store-Records-Reports-Menu', 'name' => 'View Store Records Reports Menu'],
            ['slug' => 'View-Raw-Material-Issue-Menu', 'name' => 'View Raw Material Issue Menu'],
            ['slug' => 'View-Loss-Prevention-Stock-Audits-Menu', 'name' => 'View Loss Prevention Stock Audits Menu'],
            ['slug' => 'View-Raw-Materials-All', 'name' => 'View Raw Materials All'],
            ['slug' => 'View-Raw-Materials-Company', 'name' => 'View Raw Materials Company'],
            ['slug' => 'View-Raw-Materials-Unit', 'name' => 'View Raw Materials Unit'],
            ['slug' => 'View-Raw-Materials', 'name' => 'View Raw Materials'],
            ['slug' => 'Register-Raw-Materials', 'name' => 'Register Raw Materials'],
            ['slug' => 'Edit-Raw-Materials', 'name' => 'Edit Raw Materials'],
            ['slug' => 'Delete-Raw-Materials', 'name' => 'Delete Raw Materials'],
            ['slug' => 'View-Vendors', 'name' => 'View Vendors'],
            ['slug' => 'Register-Vendors', 'name' => 'Register Vendors'],
            ['slug' => 'Edit-Vendors', 'name' => 'Edit Vendors'],
            ['slug' => 'Delete-Vendors', 'name' => 'Delete Vendors'],
            ['slug' => 'View-Purchase-Orders', 'name' => 'View Purchase Orders'],
            ['slug' => 'Register-Purchase-Orders', 'name' => 'Register Purchase Orders'],
            ['slug' => 'Edit-Purchase-Orders', 'name' => 'Edit Purchase Orders'],
            ['slug' => 'Delete-Purchase-Orders', 'name' => 'Delete Purchase Orders'],
            ['slug' => 'View-Contracts', 'name' => 'View Contracts'],
            ['slug' => 'Register-Contracts', 'name' => 'Register Contracts'],
            ['slug' => 'Edit-Contracts', 'name' => 'Edit Contracts'],
            ['slug' => 'Delete-Contracts', 'name' => 'Delete Contracts'],
            ['slug' => 'View-Raw-Materials-Purchase', 'name' => 'View Raw Materials Purchase'],
            ['slug' => 'Register-Raw-Materials-Purchase', 'name' => 'Register Raw Materials Purchase'],
            ['slug' => 'Edit-Raw-Materials-Purchase', 'name' => 'Edit Raw Materials Purchase'],
            ['slug' => 'Delete-Raw-Materials-Purchase', 'name' => 'Delete Raw Materials Purchase'],
            ['slug' => 'View-Raw-Material-Stock', 'name' => 'View Raw Material Stock'],
            ['slug' => 'View-Raw-Material-Issues', 'name' => 'View Raw Material Issues'],
            ['slug' => 'Register-Raw-Material-Issues', 'name' => 'Register Raw Material Issues'],
            ['slug' => 'Edit-Raw-Material-Issues', 'name' => 'Edit Raw Material Issues'],
            ['slug' => 'Delete-Raw-Material-Issues', 'name' => 'Delete Raw Material Issues'],
            ['slug' => 'View-Store-Records-Reports', 'name' => 'View Store Records Reports'],
            ['slug' => 'View-Stock-Audits', 'name' => 'View Stock Audits'],
            ['slug' => 'Register-Stock-Audits', 'name' => 'Register Stock Audits'],
            ['slug' => 'Edit-Stock-Audits', 'name' => 'Edit Stock Audits'],
            ['slug' => 'Delete-Stock-Audits', 'name' => 'Delete Stock Audits'],
            ['slug' => 'View-Loss-Prevention', 'name' => 'View Loss Prevention'],
            ['slug' => 'View-Sales-Management', 'name' => 'View Sales Management'],
            ['slug' => 'View-Sales-Modules', 'name' => 'View Sales Modules'],
            ['slug' => 'Create-Sales-Data', 'name' => 'Create Sales Data'],
            ['slug' => 'Edit-Sales-Data', 'name' => 'Edit Sales Data'],
            ['slug' => 'Delete-Sales-Data', 'name' => 'Delete Sales Data'],
            ['slug' => 'View-Customer-Contacts-Menu', 'name' => 'View Customer Contacts Menu'],
            ['slug' => 'View-Customer-Contacts', 'name' => 'View Customer Contacts'],
            ['slug' => 'Register-Customer-Contacts', 'name' => 'Register Customer Contacts'],
            ['slug' => 'Edit-Customer-Contacts', 'name' => 'Edit Customer Contacts'],
            ['slug' => 'Delete-Customer-Contacts', 'name' => 'Delete Customer Contacts'],
            ['slug' => 'View-Campaigns', 'name' => 'View Marketing Campaigns'],
            ['slug' => 'Register-Campaigns', 'name' => 'Register Marketing Campaigns'],
            ['slug' => 'Edit-Campaigns', 'name' => 'Edit Marketing Campaigns'],
            ['slug' => 'Delete-Campaigns', 'name' => 'Delete Marketing Campaigns'],
            ['slug' => 'View-CampaignResponses', 'name' => 'View Campaign Responses'],
            ['slug' => 'Register-CampaignResponses', 'name' => 'Register Campaign Responses'],
            ['slug' => 'Edit-CampaignResponses', 'name' => 'Edit Campaign Responses'],
            ['slug' => 'Delete-CampaignResponses', 'name' => 'Delete Campaign Responses'],
            ['slug' => 'View-Opportunities', 'name' => 'View Opportunities'],
            ['slug' => 'Register-Opportunities', 'name' => 'Register Opportunities'],
            ['slug' => 'Edit-Opportunities', 'name' => 'Edit Opportunities'],
            ['slug' => 'Delete-Opportunities', 'name' => 'Delete Opportunities'],
            ['slug' => 'Close-Opportunity', 'name' => 'Close/Win Opportunity'],
            ['slug' => 'View-Proforma', 'name' => 'View Proforma'],
            ['slug' => 'Create-Proforma', 'name' => 'Create Proforma'],
            ['slug' => 'Edit-Proforma', 'name' => 'Edit Proforma'],
            ['slug' => 'Delete-Proforma', 'name' => 'Delete Proforma'],
            ['slug' => 'Approve-Proforma', 'name' => 'Approve Proforma'],
            ['slug' => 'Post-Accounting', 'name' => 'Post Accounting'],
            ['slug' => 'View-Deliveries', 'name' => 'View Deliveries'],
            ['slug' => 'Register-Deliveries', 'name' => 'Register Deliveries'],
            ['slug' => 'Edit-Deliveries', 'name' => 'Edit Deliveries'],
            ['slug' => 'Delete-Deliveries', 'name' => 'Delete Deliveries'],
            ['slug' => 'View-Invoices', 'name' => 'View Invoices'],
            ['slug' => 'Register-Invoices', 'name' => 'Register Invoices'],
            ['slug' => 'Edit-Invoices', 'name' => 'Edit Invoices'],
            ['slug' => 'Delete-Invoices', 'name' => 'Delete Invoices'],
            ['slug' => 'View-Payments', 'name' => 'View Payments'],
            ['slug' => 'Create-Payments', 'name' => 'Create Payments'],
            ['slug' => 'Update-Payments', 'name' => 'Update Payments'],
            ['slug' => 'Delete-Payments', 'name' => 'Delete Payments'],
            ['slug' => 'Verify-Payments', 'name' => 'Verify Payments'],
            ['slug' => 'Print-Payments', 'name' => 'Print Payments'],
            ['slug' => 'Export-Payments-PDF', 'name' => 'Export Payments PDF'],
            ['slug' => 'View-Credit-Notes', 'name' => 'View Credit Notes'],
            ['slug' => 'Register-Credit-Notes', 'name' => 'Register Credit Notes'],
            ['slug' => 'Edit-Credit-Notes', 'name' => 'Edit Credit Notes'],
            ['slug' => 'Delete-Credit-Notes', 'name' => 'Delete Credit Notes'],
            ['slug' => 'View-POS-Sales', 'name' => 'View POS Sales'],
            ['slug' => 'Register-POS-Sales', 'name' => 'Register POS Sales'],
            ['slug' => 'Edit-POS-Sales', 'name' => 'Edit POS Sales'],
            ['slug' => 'Delete-POS-Sales', 'name' => 'Delete POS Sales'],
            ['slug' => 'View-Cash-Sales', 'name' => 'View Cash Sales'],
            ['slug' => 'Register-Cash-Sales', 'name' => 'Register Cash Sales'],
            ['slug' => 'Edit-Cash-Sales', 'name' => 'Edit Cash Sales'],
            ['slug' => 'Delete-Cash-Sales', 'name' => 'Delete Cash Sales'],
            ['slug' => 'View-Activities', 'name' => 'View Activities'],
            ['slug' => 'Register-Activities', 'name' => 'Register Activities'],
            ['slug' => 'Edit-Activities', 'name' => 'Edit Activities'],
            ['slug' => 'Delete-Activities', 'name' => 'Delete Activities'],
            ['slug' => 'View-Sales-Reports', 'name' => 'View Sales Reports'],
            ['slug' => 'View-Sales-Summary', 'name' => 'View Sales Summary Report'],
            ['slug' => 'View-Sales-TopCustomers', 'name' => 'View Top Customers Report'],
            ['slug' => 'View-Sales-ByProduct', 'name' => 'View Sales by Product Report'],
            ['slug' => 'View-Sales-Campaigns', 'name' => 'View Campaign Performance Report'],
            ['slug' => 'View-Sales-Quotes', 'name' => 'View Quotes Report'],
            ['slug' => 'View-Sales-Activities', 'name' => 'View Activities Report'],
            ['slug' => 'View-Sales-Orders', 'name' => 'View Sales Orders'],
            ['slug' => 'Create-Sales-Orders', 'name' => 'Create Sales Orders'],
            ['slug' => 'Edit-Sales-Orders', 'name' => 'Edit Sales Orders'],
            ['slug' => 'Delete-Sales-Orders', 'name' => 'Delete Sales Orders'],
            ['slug' => 'Approve-Sales-Orders', 'name' => 'Approve Sales Orders'],
            ['slug' => 'Add-Sales-Items', 'name' => 'Add Sales Items'],
            ['slug' => 'Delete-Sales-Items', 'name' => 'Delete Sales Items'],
            ['slug' => 'Approve-Payments', 'name' => 'Approve Payments'],
            ['slug' => 'Access-Payment-Form', 'name' => 'Access Payment Form'],
            ['slug' => 'View-Attachments', 'name' => 'View Attachments'],
            ['slug' => 'Upload-Attachments', 'name' => 'Upload Attachments'],
            ['slug' => 'Download-Attachments', 'name' => 'Download Attachments'],
            ['slug' => 'Delete-Attachments', 'name' => 'Delete Attachments'],
            ['slug' => 'Approve-Attachments', 'name' => 'Approve Attachments'],
            ['slug' => 'View-Customers', 'name' => 'View Customers'],
            ['slug' => 'Create-Customers', 'name' => 'Create Customers'],
            ['slug' => 'Edit-Customers', 'name' => 'Edit Customers'],
            ['slug' => 'Delete-Customers', 'name' => 'Delete Customers'],
            ['slug' => 'Access-Edit-Customer', 'name' => 'Access Edit Customer Page'],
            ['slug' => 'Export-Sales-Reports', 'name' => 'Export Sales Reports'],
            ['slug' => 'Auditing-Modules', 'name' => 'View Auditing Modules'],
            ['slug' => 'QualityAssurance-Modules', 'name' => 'View Quality Assurance Modules'],
            ['slug' => 'Microfinancing-Modules', 'name' => 'View Microfinancing Modules'],
            ['slug' => 'View-Microfinancing-Menu', 'name' => 'View Microfinancing Menu'],
            ['slug' => 'View-Other-Microfinancing-Menu', 'name' => 'View Other Microfinancing Menu'],
            ['slug' => 'View-CashPoint-Menu', 'name' => 'View Cash Point Menu'],
            ['slug' => 'View-BankNetwork', 'name' => 'View Bank & Network'],
            ['slug' => 'Register-BankNetwork', 'name' => 'Register Bank & Network'],
            ['slug' => 'Edit-BankNetwork', 'name' => 'Edit Bank & Network'],
            ['slug' => 'Delete-BankNetwork', 'name' => 'Delete Bank & Network'],
            ['slug' => 'View-Microfinancing-Transaction', 'name' => 'View Microfinancing Transactions'],
            ['slug' => 'Register-Microfinancing-Transaction', 'name' => 'Register Microfinancing Transactions'],
            ['slug' => 'Edit-Microfinancing-Transaction', 'name' => 'Edit Microfinancing Transactions'],
            ['slug' => 'Delete-Microfinancing-Transaction', 'name' => 'Delete Microfinancing Transactions'],
            ['slug' => 'View-Microfinance-Dashboard', 'name' => 'View Microfinance Dashboard'],
            ['slug' => 'View-Loan-Menu', 'name' => 'View Loan Menu'],
            ['slug' => 'View-Microfinance-Settings', 'name' => 'View Microfinance Settings'],
            ['slug' => 'Register-Microfinance-Settings', 'name' => 'Register Microfinance Settings'],
            ['slug' => 'Edit-Microfinance-Settings', 'name' => 'Edit Microfinance Settings'],
            ['slug' => 'View-Loan-Categories', 'name' => 'View Loan Categories'],
            ['slug' => 'Register-Loan-Categories', 'name' => 'Register Loan Categories'],
            ['slug' => 'Edit-Loan-Categories', 'name' => 'Edit Loan Categories'],
            ['slug' => 'Delete-Loan-Categories', 'name' => 'Delete Loan Categories'],
            ['slug' => 'View-Loan-Products', 'name' => 'View Loan Products'],
            ['slug' => 'Register-Loan-Products', 'name' => 'Register Loan Products'],
            ['slug' => 'Edit-Loan-Products', 'name' => 'Edit Loan Products'],
            ['slug' => 'Delete-Loan-Products', 'name' => 'Delete Loan Products'],
            ['slug' => 'View-Loan-Applicants', 'name' => 'View Loan Applicants'],
            ['slug' => 'Register-Loan-Applicants', 'name' => 'Register Loan Applicants'],
            ['slug' => 'Edit-Loan-Applicants', 'name' => 'Edit Loan Applicants'],
            ['slug' => 'Delete-Loan-Applicants', 'name' => 'Delete Loan Applicants'],
            ['slug' => 'View-Loan-Applications', 'name' => 'View Loan Applications'],
            ['slug' => 'Register-Loan-Applications', 'name' => 'Register Loan Applications'],
            ['slug' => 'Edit-Loan-Applications', 'name' => 'Edit Loan Applications'],
            ['slug' => 'Delete-Loan-Applications', 'name' => 'Delete Loan Applications'],
            ['slug' => 'Verify-Loan-Applications', 'name' => 'Verify Loan Applications'],
            ['slug' => 'Approve-Loan-Applications', 'name' => 'Approve Loan Applications'],
            ['slug' => 'Decline-Loan-Applications', 'name' => 'Decline Loan Applications'],
            ['slug' => 'Reject-Loan-Applications', 'name' => 'Reject Loan Applications'],
            ['slug' => 'Cashout-Loan-Applications', 'name' => 'Cashout Loan Applications'],
            ['slug' => 'View-Loan-Repayments', 'name' => 'View Loan Repayments'],
            ['slug' => 'Register-Loan-Repayments', 'name' => 'Register Loan Repayments'],
            ['slug' => 'Edit-Loan-Repayments', 'name' => 'Edit Loan Repayments'],
            ['slug' => 'Delete-Loan-Repayments', 'name' => 'Delete Loan Repayments'],
            ['slug' => 'View-Loan-Penalties', 'name' => 'View Loan Penalties'],
            ['slug' => 'Register-Loan-Penalties', 'name' => 'Register Loan Penalties'],
            ['slug' => 'Edit-Loan-Penalties', 'name' => 'Edit Loan Penalties'],
            ['slug' => 'Delete-Loan-Penalties', 'name' => 'Delete Loan Penalties'],
            ['slug' => 'View-Loan-Collateral', 'name' => 'View Loan Collateral'],
            ['slug' => 'Register-Loan-Collateral', 'name' => 'Register Loan Collateral'],
            ['slug' => 'Edit-Loan-Collateral', 'name' => 'Edit Loan Collateral'],
            ['slug' => 'Delete-Loan-Collateral', 'name' => 'Delete Loan Collateral'],
            ['slug' => 'View-Loan-Attachments', 'name' => 'View Loan Attachments'],
            ['slug' => 'Register-Loan-Attachments', 'name' => 'Register Loan Attachments'],
            ['slug' => 'Delete-Loan-Attachments', 'name' => 'Delete Loan Attachments'],
            ['slug' => 'View-Loan-Reminders', 'name' => 'View Loan Reminders'],
            ['slug' => 'Send-Loan-Reminders', 'name' => 'Send Loan Reminders'],
            ['slug' => 'View-Microfinance-Costs', 'name' => 'View Microfinance Costs'],
            ['slug' => 'Register-Microfinance-Costs', 'name' => 'Register Microfinance Costs'],
            ['slug' => 'Edit-Microfinance-Costs', 'name' => 'Edit Microfinance Costs'],
            ['slug' => 'Delete-Microfinance-Costs', 'name' => 'Delete Microfinance Costs'],
            ['slug' => 'View-Microfinance-Other-Income', 'name' => 'View Microfinance Other Income'],
            ['slug' => 'Register-Microfinance-Other-Income', 'name' => 'Register Microfinance Other Income'],
            ['slug' => 'Edit-Microfinance-Other-Income', 'name' => 'Edit Microfinance Other Income'],
            ['slug' => 'Delete-Microfinance-Other-Income', 'name' => 'Delete Microfinance Other Income'],
            ['slug' => 'View-Microfinancing-Reports', 'name' => 'View Microfinancing Reports'],
            ['slug' => 'Consultancy-Modules', 'name' => 'View Consultancy Modules'],
            ['slug' => 'Reporting-Modules', 'name' => 'View Reporting Modules'],
            ['slug' => 'Requisition-Modules', 'name' => 'View Requisition & Approvals Modules'],
            ['slug' => 'View-Requisition-Menu', 'name' => 'View Requisition Menu'],
            ['slug' => 'View-MoneyRequest', 'name' => 'View Money Requests'],
            ['slug' => 'View-All-MoneyRequest', 'name' => 'View All Money Requests'],
            ['slug' => 'View-Company-MoneyRequest', 'name' => 'View Company Money Requests'],
            ['slug' => 'View-Unit-MoneyRequest', 'name' => 'View Unit Money Requests'],
            ['slug' => 'Register-MoneyRequest', 'name' => 'Create Money Requests'],
            ['slug' => 'Edit-MoneyRequest', 'name' => 'Edit Money Requests'],
            ['slug' => 'Delete-MoneyRequest', 'name' => 'Delete Money Requests'],
            ['slug' => 'Print-MoneyRequest', 'name' => 'Print Money Requests'],
            ['slug' => 'Verify-MoneyRequest', 'name' => 'Verify Money Requests'],
            ['slug' => 'Approve-MoneyRequest', 'name' => 'Approve Money Requests'],
            ['slug' => 'CashOut-MoneyRequest', 'name' => 'Cash Out Money Requests'],
            ['slug' => 'Retirement-MoneyRequest', 'name' => 'Retirement Of Money Requests'],
            ['slug' => 'View-Requisition-Reports', 'name' => 'View Requisition Reports'],
            ['slug' => 'View-Cashed-Out&Retirement-Money-Request-Report', 'name' => 'View Cashed-Out & Retirement Money Request Report'],
            ['slug' => 'View-Retirement-Money-Request-Document', 'name' => 'View Retirement Money Request Document'],
            ['slug' => 'View-Requistion-Book-Details', 'name' => 'View Requisition Book Details'],
            ['slug' => 'View-Stock-Movement', 'name' => 'View Stock Movement'],
            ['slug' => 'Create-Stock-Movement', 'name' => 'Create Stock Movement'],
            ['slug' => 'Edit-Stock-Movement', 'name' => 'Edit Stock Movement'],
            ['slug' => 'Delete-Stock-Movement', 'name' => 'Delete Stock Movement'],
            ['slug' => 'View-Store-Requests', 'name' => 'View Store Requests'],
            ['slug' => 'Create-Store-Requests', 'name' => 'Create Store Requests'],
            ['slug' => 'Approve-Store-Requests', 'name' => 'Approve Store Requests'],
            ['slug' => 'Delete-Store-Requests', 'name' => 'Delete Store Requests'],
            ['slug' => 'View-Inventory-Reports', 'name' => 'View Inventory Reports'],
            ['slug' => 'Export-Inventory-Reports', 'name' => 'Export Inventory Reports'],
            ['slug' => 'Print-Inventory-Reports', 'name' => 'Print Inventory Reports'],
            ['slug' => 'View-Stock-Batches', 'name' => 'View Stock Batches'],
            ['slug' => 'Create-Stock-Batches', 'name' => 'Create Stock Batches'],
            ['slug' => 'Edit-Stock-Batches', 'name' => 'Edit Stock Batches'],
            ['slug' => 'Delete-Stock-Batches', 'name' => 'Delete Stock Batches'],
            ['slug' => 'View-Stock-Adjustments', 'name' => 'View Stock Adjustments'],
            ['slug' => 'Create-Stock-Adjustments', 'name' => 'Create Stock Adjustments'],
            ['slug' => 'Edit-Stock-Adjustments', 'name' => 'Edit Stock Adjustments'],
            ['slug' => 'Delete-Stock-Adjustments', 'name' => 'Delete Stock Adjustments'],
            ['slug' => 'Approve-Stock-Adjustments', 'name' => 'Approve Stock Adjustments'],
            ['slug' => 'View-Goods-Receipts', 'name' => 'View Goods Receipts'],
            ['slug' => 'Create-Goods-Receipts', 'name' => 'Create Goods Receipts'],
            ['slug' => 'Edit-Goods-Receipts', 'name' => 'Edit Goods Receipts'],
            ['slug' => 'Delete-Goods-Receipts', 'name' => 'Delete Goods Receipts'],
            ['slug' => 'Approve-Goods-Receipts', 'name' => 'Approve Goods Receipts'],
            ['slug' => 'View-Goods-Receipt-Items', 'name' => 'View Goods Receipt Items'],
            ['slug' => 'Create-Goods-Receipt-Items', 'name' => 'Create Goods Receipt Items'],
            ['slug' => 'Edit-Goods-Receipt-Items', 'name' => 'Edit Goods Receipt Items'],
            ['slug' => 'Delete-Goods-Receipt-Items', 'name' => 'Delete Goods Receipt Items'],
            ['slug' => 'View-Purchase-Requisitions', 'name' => 'View Purchase Requisitions'],
            ['slug' => 'Create-Purchase-Requisitions', 'name' => 'Create Purchase Requisitions'],
            ['slug' => 'Edit-Purchase-Requisitions', 'name' => 'Edit Purchase Requisitions'],
            ['slug' => 'Delete-Purchase-Requisitions', 'name' => 'Delete Purchase Requisitions'],
            ['slug' => 'Approve-Purchase-Requisitions', 'name' => 'Approve Purchase Requisitions'],
            ['slug' => 'View-Purchase-Requisition-Items', 'name' => 'View Purchase Requisition Items'],
            ['slug' => 'Create-Purchase-Requisition-Items', 'name' => 'Create Purchase Requisition Items'],
            ['slug' => 'Edit-Purchase-Requisition-Items', 'name' => 'Edit Purchase Requisition Items'],
            ['slug' => 'Delete-Purchase-Requisition-Items', 'name' => 'Delete Purchase Requisition Items'],
            ['slug' => 'View-Purchase-Quotations', 'name' => 'View Purchase Quotations'],
            ['slug' => 'Create-Purchase-Quotations', 'name' => 'Create Purchase Quotations'],
            ['slug' => 'Edit-Purchase-Quotations', 'name' => 'Edit Purchase Quotations'],
            ['slug' => 'Delete-Purchase-Quotations', 'name' => 'Delete Purchase Quotations'],
            ['slug' => 'Approve-Purchase-Quotations', 'name' => 'Approve Purchase Quotations'],
            ['slug' => 'View-Purchase-Quotation-Items', 'name' => 'View Purchase Quotation Items'],
            ['slug' => 'Create-Purchase-Quotation-Items', 'name' => 'Create Purchase Quotation Items'],
            ['slug' => 'Edit-Purchase-Quotation-Items', 'name' => 'Edit Purchase Quotation Items'],
            ['slug' => 'Delete-Purchase-Quotation-Items', 'name' => 'Delete Purchase Quotation Items'],
            ['slug' => 'View-Supplier-Payments', 'name' => 'View Supplier Payments'],
            ['slug' => 'Create-Supplier-Payments', 'name' => 'Create Supplier Payments'],
            ['slug' => 'Edit-Supplier-Payments', 'name' => 'Edit Supplier Payments'],
            ['slug' => 'Delete-Supplier-Payments', 'name' => 'Delete Supplier Payments'],
            ['slug' => 'Approve-Supplier-Payments', 'name' => 'Approve Supplier Payments'],
            ['slug' => 'View-Supplier-Invoices', 'name' => 'View Supplier Invoices'],
            ['slug' => 'Create-Supplier-Invoices', 'name' => 'Create Supplier Invoices'],
            ['slug' => 'Edit-Supplier-Invoices', 'name' => 'Edit Supplier Invoices'],
            ['slug' => 'Delete-Supplier-Invoices', 'name' => 'Delete Supplier Invoices'],
            ['slug' => 'Approve-Supplier-Invoices', 'name' => 'Approve Supplier Invoices'],
            ['slug' => 'View-Debit-Notes', 'name' => 'View Debit Notes'],
            ['slug' => 'Create-Debit-Notes', 'name' => 'Create Debit Notes'],
            ['slug' => 'Edit-Debit-Notes', 'name' => 'Edit Debit Notes'],
            ['slug' => 'Delete-Debit-Notes', 'name' => 'Delete Debit Notes'],
            ['slug' => 'View-Sales-Types', 'name' => 'View Sales Types'],
            ['slug' => 'Create-Sales-Types', 'name' => 'Create Sales Types'],
            ['slug' => 'Edit-Sales-Types', 'name' => 'Edit Sales Types'],
            ['slug' => 'Delete-Sales-Types', 'name' => 'Delete Sales Types'],
            ['slug' => 'View-CRM-Reports', 'name' => 'View CRM Reports'],
            ['slug' => 'Export-CRM-Reports', 'name' => 'Export CRM Reports'],
            ['slug' => 'Print-CRM-Reports', 'name' => 'Print CRM Reports'],
            ['slug' => 'View-Communications', 'name' => 'View Communications'],
            ['slug' => 'Create-Communications', 'name' => 'Create Communications'],
            ['slug' => 'Edit-Communications', 'name' => 'Edit Communications'],
            ['slug' => 'Delete-Communications', 'name' => 'Delete Communications'],
            ['slug' => 'View-Followups', 'name' => 'View Followups'],
            ['slug' => 'Create-Followups', 'name' => 'Create Followups'],
            ['slug' => 'Edit-Followups', 'name' => 'Edit Followups'],
            ['slug' => 'Delete-Followups', 'name' => 'Delete Followups'],
            ['slug' => 'View-Leads', 'name' => 'View Leads'],
            ['slug' => 'Create-Leads', 'name' => 'Create Leads'],
            ['slug' => 'Edit-Leads', 'name' => 'Edit Leads'],
            ['slug' => 'Delete-Leads', 'name' => 'Delete Leads'],
            ['slug' => 'View-Pipelines', 'name' => 'View Pipelines'],
            ['slug' => 'Create-Pipelines', 'name' => 'Create Pipelines'],
            ['slug' => 'Edit-Pipelines', 'name' => 'Edit Pipelines'],
            ['slug' => 'Delete-Pipelines', 'name' => 'Delete Pipelines'],
            ['slug' => 'View-Quotes', 'name' => 'View Quotes'],
            ['slug' => 'Create-Quotes', 'name' => 'Create Quotes'],
            ['slug' => 'Edit-Quotes', 'name' => 'Edit Quotes'],
            ['slug' => 'Delete-Quotes', 'name' => 'Delete Quotes'],
            ['slug' => 'Approve-Quotes', 'name' => 'Approve Quotes'],
            ['slug' => 'View-Quote-Items', 'name' => 'View Quote Items'],
            ['slug' => 'Create-Quote-Items', 'name' => 'Create Quote Items'],
            ['slug' => 'Edit-Quote-Items', 'name' => 'Edit Quote Items'],
            ['slug' => 'Delete-Quote-Items', 'name' => 'Delete Quote Items'],
            ['slug' => 'View-POS-Reports', 'name' => 'View POS Reports'],
            ['slug' => 'Export-POS-Reports', 'name' => 'Export POS Reports'],
            ['slug' => 'Print-POS-Reports', 'name' => 'Print POS Reports'],
            ['slug' => 'View-Delivery-Items', 'name' => 'View Delivery Items'],
            ['slug' => 'Create-Delivery-Items', 'name' => 'Create Delivery Items'],
            ['slug' => 'Edit-Delivery-Items', 'name' => 'Edit Delivery Items'],
            ['slug' => 'Delete-Delivery-Items', 'name' => 'Delete Delivery Items'],
            ['slug' => 'View-Invoice-Items', 'name' => 'View Invoice Items'],
            ['slug' => 'Create-Invoice-Items', 'name' => 'Create Invoice Items'],
            ['slug' => 'Edit-Invoice-Items', 'name' => 'Edit Invoice Items'],
            ['slug' => 'Delete-Invoice-Items', 'name' => 'Delete Invoice Items'],
            ['slug' => 'Register-Customers', 'name' => 'Register Customers'],
            ['slug' => 'Register-Quotes', 'name' => 'Register Quotes'],
            ['slug' => 'Approve-Quote', 'name' => 'Approve/Accept Quote'],
            ['slug' => 'View-Proformas', 'name' => 'View Proformas'],
            ['slug' => 'Register-Proformas', 'name' => 'Register Proformas'],
            ['slug' => 'Edit-Proformas', 'name' => 'Edit Proformas'],
            ['slug' => 'Delete-Proformas', 'name' => 'Delete Proformas'],
            ['slug' => 'Register-Sales-Orders', 'name' => 'Register Sales Orders'],
            ['slug' => 'Register-Payments', 'name' => 'Register Payments'],
            ['slug' => 'Edit-Payments', 'name' => 'Edit Payments'],
            ['slug' => 'Manage-Stock-Movement', 'name' => 'Manage Stock Movement'],
            ['slug' => 'Export-Stock', 'name' => 'Export Stock'],
            ['slug' => 'View-Products', 'name' => 'View Products'],
            ['slug' => 'Create-Product', 'name' => 'Create Product'],
            ['slug' => 'Manage-Product', 'name' => 'Manage Product'],
            ['slug' => 'Print-Product', 'name' => 'Print Product'],
            ['slug' => 'Export-Product', 'name' => 'Export Product'],
            ['slug' => 'View-Sales-Dashboard', 'name' => 'View Sales Dashboard'],
            ['slug' => 'Create-Contacts', 'name' => 'Create Contacts'],
            ['slug' => 'Edit-Contacts', 'name' => 'Edit Contacts'],
            ['slug' => 'Delete-Contacts', 'name' => 'Delete Contacts'],
            ['slug' => 'Create-Campaigns', 'name' => 'Create Campaigns'],
            ['slug' => 'Create-Opportunities', 'name' => 'Create Opportunities'],
            ['slug' => 'Create-Proformas', 'name' => 'Create Proformas'],
            ['slug' => 'Approve-Proformas', 'name' => 'Approve Proformas'],
            ['slug' => 'Confirm-Sales-Orders', 'name' => 'Confirm Sales Orders'],
            ['slug' => 'Cancel-Sales-Orders', 'name' => 'Cancel Sales Orders'],
            ['slug' => 'Create-Deliveries', 'name' => 'Create Deliveries'],
            ['slug' => 'Dispatch-Deliveries', 'name' => 'Dispatch Deliveries'],
            ['slug' => 'Create-Invoices', 'name' => 'Create Invoices'],
            ['slug' => 'Post-Invoices', 'name' => 'Post Invoices'],
            ['slug' => 'Receive-Payments', 'name' => 'Receive Payments'],
            ['slug' => 'Create-Credit-Notes', 'name' => 'Create Credit Notes'],
            ['slug' => 'Approve-Credit-Notes', 'name' => 'Approve Credit Notes'],
            ['slug' => 'Post-Credit-Notes', 'name' => 'Post Credit Notes'],
            ['slug' => 'Create-POS-Sales', 'name' => 'Create POS Sales'],
            ['slug' => 'Create-Cash-Sales', 'name' => 'Create Cash Sales'],
            ['slug' => 'Approve-Cash-Sales', 'name' => 'Approve Cash Sales'],
            ['slug' => 'Post-Cash-Sales', 'name' => 'Post Cash Sales'],
            ['slug' => 'Create-Activities', 'name' => 'Create Activities'],
            ['slug' => 'Approve-Activities', 'name' => 'Approve Activities'],
            ['slug' => 'View-Suppliers', 'name' => 'View Suppliers'],
            ['slug' => 'Create-Suppliers', 'name' => 'Create Suppliers'],
            ['slug' => 'Edit-Suppliers', 'name' => 'Edit Suppliers'],
            ['slug' => 'Delete-Suppliers', 'name' => 'Delete Suppliers'],
            ['slug' => 'Create-Purchase-Invoice', 'name' => 'Create Purchase Invoice'],
            ['slug' => 'Pay-Purchase-Invoice', 'name' => 'Pay Purchase Invoice'],
            ['slug' => 'View-Purchasing-Dashboard', 'name' => 'View Purchasing Dashboard'],
            ['slug' => 'Receive-Goods', 'name' => 'Receive Goods'],
            ['slug' => 'View-Purchase-Invoices', 'name' => 'View Purchase Invoices'],
            ['slug' => 'View-Stock', 'name' => 'View Stock'],
            ['slug' => 'Stock-Movement', 'name' => 'Stock Movement'],
            ['slug' => 'Adjust-Stock', 'name' => 'Adjust Stock'],
            ['slug' => 'Receive-Stock', 'name' => 'Receive Stock'],
            ['slug' => 'View-Items', 'name' => 'View Items'],
            ['slug' => 'Create-Items', 'name' => 'Create Items'],
            ['slug' => 'Edit-Items', 'name' => 'Edit Items'],
            ['slug' => 'Delete-Items', 'name' => 'Delete Items'],
            ['slug' => 'View-Finance', 'name' => 'View Finance'],
            ['slug' => 'Post-Transactions', 'name' => 'Post Transactions'],
            ['slug' => 'View-Ledger', 'name' => 'View Ledger'],
            ['slug' => 'View-Accounting-Entries', 'name' => 'View Accounting Entries'],
            ['slug' => 'View-Profit-Report', 'name' => 'View Profit Report'],
            ['slug' => 'Export-Reports', 'name' => 'Export Reports'],
            ['slug' => 'Print-Reports', 'name' => 'Print Reports'],
            ['slug' => 'View-Analytics', 'name' => 'View Analytics'],
            ['slug' => 'View-Companies', 'name' => 'View Companies'],
            ['slug' => 'Manage-Companies', 'name' => 'Manage Companies'],
            ['slug' => 'Switch-Branch', 'name' => 'Switch Branch'],
            ['slug' => 'View-Users', 'name' => 'View Users'],
            ['slug' => 'Create-Users', 'name' => 'Create Users'],
            ['slug' => 'Edit-Users', 'name' => 'Edit Users'],
            ['slug' => 'Delete-Users', 'name' => 'Delete Users'],
            ['slug' => 'Assign-Roles', 'name' => 'Assign Roles'],
            ['slug' => 'Create-Campaign', 'name' => 'Create Campaign'],
            ['slug' => 'Edit-Campaign', 'name' => 'Edit Campaign'],
            ['slug' => 'Delete-Campaign', 'name' => 'Delete Campaign'],
            ['slug' => 'Apply-Campaign', 'name' => 'Apply Campaign'],
            ['slug' => 'View-Campaign-Reports', 'name' => 'View Campaign Reports'],
            ['slug' => 'View-Delivery', 'name' => 'View Delivery'],
            ['slug' => 'Create-Delivery', 'name' => 'Create Delivery'],
            ['slug' => 'Edit-Delivery', 'name' => 'Edit Delivery'],
            ['slug' => 'Delete-Delivery', 'name' => 'Delete Delivery'],
            ['slug' => 'Create-Sale', 'name' => 'Create Sale'],
            ['slug' => 'View-Sales', 'name' => 'View Sales'],
            ['slug' => 'Delete-Sale', 'name' => 'Delete Sale'],
            ['slug' => 'Create-POS-Sale', 'name' => 'Create POS Sale'],
            ['slug' => 'Create-Cash-Sale', 'name' => 'Create Cash Sale'],
            ['slug' => 'Create-Invoice', 'name' => 'Create Invoice'],
            ['slug' => 'Approve-Invoice', 'name' => 'Approve Invoice'],
            ['slug' => 'View-Financial-Reports', 'name' => 'View Financial Reports'],
            ['slug' => 'View-Order-Details', 'name' => 'View Order Details'],
            ['slug' => 'Export-Orders', 'name' => 'Export Orders'],
            ['slug' => 'Access-Sales-Dashboard', 'name' => 'Access Sales Dashboard'],
            ['slug' => 'Create-Attachment', 'name' => 'Create Attachment'],
            ['slug' => 'Delete-Attachment', 'name' => 'Delete Attachment'],
            ['slug' => 'Edit-Sale', 'name' => 'Edit Order'],
            ['slug' => 'Create-Payment', 'name' => 'Add Payment'],
            ['slug' => 'Delete-Payment', 'name' => 'Delete Payment'],
            ['slug' => 'Approve-Sale', 'name' => 'Approve Attachment'],
            ['slug' => 'Edit-Notes', 'name' => 'Update Notes'],
            ['slug' => 'Verify-Payment', 'name' => 'Verify Payment'],
            ['slug' => 'Update-Invoices', 'name' => 'Update Invoices'],
            ['slug' => 'Verify-Invoices', 'name' => 'Verify Invoices'],
            ['slug' => 'Approve-Delivery', 'name' => 'Approve Delivery'],
            ['slug' => 'Dispatch-Delivery', 'name' => 'Dispatch Delivery'],
            ['slug' => 'Confirm-Delivery', 'name' => 'Confirm Delivery'],
            ['slug' => 'Create-Raw-Material-Request', 'name' => 'Create Raw Material Request'],
            ['slug' => 'Approve-Raw-Material', 'name' => 'Approve Raw Material'],
            ['slug' => 'Issue-Raw-Material', 'name' => 'Issue Raw Material'],
            ['slug' => 'View-Reports', 'name' => 'View Reports'],
            ['slug' => 'View-Proforma-Items', 'name' => 'View Proforma Items'],
            ['slug' => 'Create-Proforma-Items', 'name' => 'Create Proforma Items'],
            ['slug' => 'Edit-Proforma-Items', 'name' => 'Edit Proforma Items'],
            ['slug' => 'Delete-Proforma-Items', 'name' => 'Delete Proforma Items'],
            ['slug' => 'View-Sales-Items', 'name' => 'View Sales Items'],
            ['slug' => 'Create-Sales-Items', 'name' => 'Create Sales Items'],
            ['slug' => 'Edit-Sales-Items', 'name' => 'Edit Sales Items'],
            ['slug' => 'View-POS-Sale-Items', 'name' => 'View POS Sale Items'],
            ['slug' => 'Create-POS-Sale-Items', 'name' => 'Create POS Sale Items'],
            ['slug' => 'Edit-POS-Sale-Items', 'name' => 'Edit POS Sale Items'],
            ['slug' => 'Delete-POS-Sale-Items', 'name' => 'Delete POS Sale Items'],
            ['slug' => 'View-Cash-Purchase-Items', 'name' => 'View Cash Purchase Items'],
            ['slug' => 'Create-Cash-Purchase-Items', 'name' => 'Create Cash Purchase Items'],
            ['slug' => 'Edit-Cash-Purchase-Items', 'name' => 'Edit Cash Purchase Items'],
            ['slug' => 'Delete-Cash-Purchase-Items', 'name' => 'Delete Cash Purchase Items'],
            ['slug' => 'View-Purchase-Order-Items', 'name' => 'View Purchase Order Items'],
            ['slug' => 'Create-Purchase-Order-Items', 'name' => 'Create Purchase Order Items'],
            ['slug' => 'Edit-Purchase-Order-Items', 'name' => 'Edit Purchase Order Items'],
            ['slug' => 'Delete-Purchase-Order-Items', 'name' => 'Delete Purchase Order Items'],
            ['slug' => 'Print-Customer-Ledger', 'name' => 'Print Customer Ledger'],
            ['slug' => 'Export-Customer-Ledger', 'name' => 'Export Customer Ledger'],
            ['slug' => 'Export-Stock-Excel', 'name' => 'Export Stock Excel'],
            ['slug' => 'Export-Stock-PDF', 'name' => 'Export Stock PDF'],
            ['slug' => 'Print-Requisitions', 'name' => 'Print Requisitions'],
            ['slug' => 'Export-Requisitions', 'name' => 'Export Requisitions'],
            ['slug' => 'View-Proformas-Menu', 'name' => 'View Proformas Menu'],
            ['slug' => 'Print-Proformas', 'name' => 'Print Proformas'],
            ['slug' => 'Export-Proformas', 'name' => 'Export Proformas'],
            ['slug' => 'Register-Proforma-Items', 'name' => 'Register Proforma Items'],
            ['slug' => 'View-Sales-Orders-Menu', 'name' => 'View Sales Orders Menu'],
            ['slug' => 'Print-Sales-Orders', 'name' => 'Print Sales Orders'],
            ['slug' => 'Export-Sales-Orders', 'name' => 'Export Sales Orders'],
            ['slug' => 'View-Sales-Order-Items', 'name' => 'View Sales Order Items'],
            ['slug' => 'Register-Sales-Order-Items', 'name' => 'Register Sales Order Items'],
            ['slug' => 'Edit-Sales-Order-Items', 'name' => 'Edit Sales Order Items'],
            ['slug' => 'Delete-Sales-Order-Items', 'name' => 'Delete Sales Order Items'],
            ['slug' => 'View-Supplier-Invoices-Menu', 'name' => 'View Supplier Invoices Menu'],
            ['slug' => 'Register-Supplier-Invoices', 'name' => 'Register Supplier Invoices'],
            ['slug' => 'Print-Supplier-Invoices', 'name' => 'Print Supplier Invoices'],
            ['slug' => 'Export-Supplier-Invoices', 'name' => 'Export Supplier Invoices'],
            ['slug' => 'View-Supplier-Payments-Menu', 'name' => 'View Supplier Payments Menu'],
            ['slug' => 'Register-Supplier-Payments', 'name' => 'Register Supplier Payments'],
            ['slug' => 'Print-Supplier-Payments', 'name' => 'Print Supplier Payments'],
            ['slug' => 'Export-Supplier-Payments', 'name' => 'Export Supplier Payments'],
            ['slug' => 'Register-Goods-Receipt-Items', 'name' => 'Register Goods Receipt Items'],
            ['slug' => 'View-Goods-Receipts-Menu', 'name' => 'View Goods Receipts Menu'],
            ['slug' => 'Register-Goods-Receipts', 'name' => 'Register Goods Receipts'],
            ['slug' => 'Print-Goods-Receipts', 'name' => 'Print Goods Receipts'],
            ['slug' => 'Export-Goods-Receipts', 'name' => 'Export Goods Receipts'],
            ['slug' => 'View-Purchase-Requisitions-Menu', 'name' => 'View Purchase Requisitions Menu'],
            ['slug' => 'Register-Purchase-Requisitions', 'name' => 'Register Purchase Requisitions'],
            ['slug' => 'Print-Purchase-Requisitions', 'name' => 'Print Purchase Requisitions'],
            ['slug' => 'Export-Purchase-Requisitions', 'name' => 'Export Purchase Requisitions'],
            ['slug' => 'Register-Purchase-Requisition-Items', 'name' => 'Register Purchase Requisition Items'],
            ['slug' => 'View-Purchase-Quotations-Menu', 'name' => 'View Purchase Quotations Menu'],
            ['slug' => 'Register-Purchase-Quotations', 'name' => 'Register Purchase Quotations'],
            ['slug' => 'Print-Purchase-Quotations', 'name' => 'Print Purchase Quotations'],
            ['slug' => 'Export-Purchase-Quotations', 'name' => 'Export Purchase Quotations'],
            ['slug' => 'Register-Purchase-Quotation-Items', 'name' => 'Register Purchase Quotation Items'],
            ['slug' => 'View-Cash-Purchases-Menu', 'name' => 'View Cash Purchases Menu'],
            ['slug' => 'View-Cash-Purchases', 'name' => 'View Cash Purchases'],
            ['slug' => 'Register-Cash-Purchases', 'name' => 'Register Cash Purchases'],
            ['slug' => 'Edit-Cash-Purchases', 'name' => 'Edit Cash Purchases'],
            ['slug' => 'Delete-Cash-Purchases', 'name' => 'Delete Cash Purchases'],
            ['slug' => 'Approve-Cash-Purchases', 'name' => 'Approve Cash Purchases'],
            ['slug' => 'Print-Cash-Purchases', 'name' => 'Print Cash Purchases'],
            ['slug' => 'Export-Cash-Purchases', 'name' => 'Export Cash Purchases'],
            ['slug' => 'View-Cash-Sales-Menu', 'name' => 'View Cash Sales Menu'],
            ['slug' => 'Print-Cash-Sales', 'name' => 'Print Cash Sales'],
            ['slug' => 'Export-Cash-Sales', 'name' => 'Export Cash Sales'],
            ['slug' => 'Register-Cash-Purchase-Items', 'name' => 'Register Cash Purchase Items'],
            ['slug' => 'View-CRM-Customers-Menu', 'name' => 'View CRM Customers Menu'],
            ['slug' => 'View-Contacts-Menu', 'name' => 'View Contacts Menu'],
            ['slug' => 'View-Contacts', 'name' => 'View Contacts'],
            ['slug' => 'Register-Contacts', 'name' => 'Register Contacts'],
            ['slug' => 'Print-Contacts', 'name' => 'Print Contacts'],
            ['slug' => 'Export-Contacts', 'name' => 'Export Contacts'],
            ['slug' => 'View-Customers-Menu', 'name' => 'View Customers Menu'],
            ['slug' => 'Approve-Customers', 'name' => 'Approve Customers'],
            ['slug' => 'Print-Customers', 'name' => 'Print Customers'],
            ['slug' => 'Export-Customers', 'name' => 'Export Customers'],
            ['slug' => 'View-Leads-Menu', 'name' => 'View Leads Menu'],
            ['slug' => 'Register-Leads', 'name' => 'Register Leads'],
            ['slug' => 'Approve-Leads', 'name' => 'Approve Leads'],
            ['slug' => 'Convert-Leads', 'name' => 'Convert Leads'],
            ['slug' => 'Print-Leads', 'name' => 'Print Leads'],
            ['slug' => 'Export-Leads', 'name' => 'Export Leads'],
            ['slug' => 'View-Followups-Menu', 'name' => 'View Followups Menu'],
            ['slug' => 'Register-Followups', 'name' => 'Register Followups'],
            ['slug' => 'Complete-Followups', 'name' => 'Complete Followups'],
            ['slug' => 'Print-Followups', 'name' => 'Print Followups'],
            ['slug' => 'Export-Followups', 'name' => 'Export Followups'],
            ['slug' => 'View-Communications-Menu', 'name' => 'View Communications Menu'],
            ['slug' => 'Register-Communications', 'name' => 'Register Communications'],
            ['slug' => 'Send-Communications', 'name' => 'Send Communications'],
            ['slug' => 'Print-Communications', 'name' => 'Print Communications'],
            ['slug' => 'Export-Communications', 'name' => 'Export Communications'],
            ['slug' => 'View-Campaigns-Menu', 'name' => 'View Campaigns Menu'],
            ['slug' => 'Approve-Campaigns', 'name' => 'Approve Campaigns'],
            ['slug' => 'Launch-Campaigns', 'name' => 'Launch Campaigns'],
            ['slug' => 'Print-Campaigns', 'name' => 'Print Campaigns'],
            ['slug' => 'Export-Campaigns', 'name' => 'Export Campaigns'],
            ['slug' => 'View-Activities-Menu', 'name' => 'View Activities Menu'],
            ['slug' => 'Complete-Activities', 'name' => 'Complete Activities'],
            ['slug' => 'Print-Activities', 'name' => 'Print Activities'],
            ['slug' => 'Export-Activities', 'name' => 'Export Activities'],
            ['slug' => 'View-Opportunities-Menu', 'name' => 'View Opportunities Menu'],
            ['slug' => 'Approve-Opportunities', 'name' => 'Approve Opportunities'],
            ['slug' => 'Close-Opportunities', 'name' => 'Close Opportunities'],
            ['slug' => 'Print-Opportunities', 'name' => 'Print Opportunities'],
            ['slug' => 'Export-Opportunities', 'name' => 'Export Opportunities'],
            ['slug' => 'View-Sales-Pipeline-Menu', 'name' => 'View Sales Pipeline Menu'],
            ['slug' => 'View-Sales-Pipeline', 'name' => 'View Sales Pipeline'],
            ['slug' => 'Manage-Sales-Pipeline', 'name' => 'Manage Sales Pipeline'],
            ['slug' => 'Print-Sales-Pipeline', 'name' => 'Print Sales Pipeline'],
            ['slug' => 'Export-Sales-Pipeline', 'name' => 'Export Sales Pipeline'],
            ['slug' => 'View-Customer-Ledger-Menu', 'name' => 'View Customer Ledger Menu'],
            ['slug' => 'View-CRM-Reports-Menu', 'name' => 'View CRM Reports Menu'],
            ['slug' => 'Generate-CRM-Reports', 'name' => 'Generate CRM Reports'],
            ['slug' => 'View-Sales-Marketing-Menu', 'name' => 'View Sales Marketing Menu'],
            ['slug' => 'View-Purchase-Procurement-Menu', 'name' => 'View Purchase Procurement Menu'],
            ['slug' => 'View-Purchase-Dashboard', 'name' => 'View Purchase Dashboard'],
            ['slug' => 'Register-Suppliers', 'name' => 'Register Suppliers'],
            ['slug' => 'Approve-Purchase-Orders', 'name' => 'Approve Purchase Orders'],
            ['slug' => 'View-Purchase-Reports', 'name' => 'View Purchase Reports'],
            ['slug' => 'View-Inventory-Warehouse-Menu', 'name' => 'View Inventory Warehouse Menu'],
            ['slug' => 'Register-Products', 'name' => 'Register Products'],
            ['slug' => 'Edit-Products', 'name' => 'Edit Products'],
            ['slug' => 'Delete-Products', 'name' => 'Delete Products'],
            ['slug' => 'View-General-Supply-Items', 'name' => 'View General Supply Items'],
            ['slug' => 'Register-General-Supply-Items', 'name' => 'Register General Supply Items'],
            ['slug' => 'View-General-Supply-Item-Descriptions', 'name' => 'View General Supply Item Descriptions'],
            ['slug' => 'Register-General-Supply-Item-Descriptions', 'name' => 'Register General Supply Item Descriptions'],
            ['slug' => 'View-General-Supply-Receivings', 'name' => 'View General Supply Receivings'],
            ['slug' => 'Register-General-Supply-Receivings', 'name' => 'Register General Supply Receivings'],
            ['slug' => 'View-Stock-Ledgers', 'name' => 'View Stock Ledgers'],
            ['slug' => 'Export-Stock-Ledgers', 'name' => 'Export Stock Ledgers'],
            ['slug' => 'View-General-Supply-Requests', 'name' => 'View General Supply Requests'],
            ['slug' => 'Register-General-Supply-Requests', 'name' => 'Register General Supply Requests'],
            ['slug' => 'View-Audits-Compliance-Menu', 'name' => 'View Audits Compliance Menu'],
            ['slug' => 'View-Compliance-Reports', 'name' => 'View Compliance Reports'],
            ['slug' => 'Export-Compliance-Reports', 'name' => 'Export Compliance Reports'],
            ['slug' => 'View-Audit-Logs', 'name' => 'View Audit Logs'],
            ['slug' => 'View-Drilling-Blasting-Menu', 'name' => 'View Drilling & Blasting Menu'],
            ['slug' => 'View-Drilling-Blasting', 'name' => 'View Drilling & Blasting'],
            ['slug' => 'Create-Drilling-Blasting', 'name' => 'Create Drilling & Blasting'],
            ['slug' => 'Edit-Drilling-Blasting', 'name' => 'Edit Drilling & Blasting'],
            ['slug' => 'Delete-Drilling-Blasting', 'name' => 'Delete Drilling & Blasting'],
            ['slug' => 'Print-Drilling-Blasting', 'name' => 'Print Drilling & Blasting'],
            ['slug' => 'View-Blasting-Summary', 'name' => 'View Blasting Summary'],
            ['slug' => 'Print-Blasting-Summary', 'name' => 'Print Blasting Summary'],


            ['slug' => 'View-Logistics-Menu', 'name' => 'View Logistics Menu'],

            ['slug' => 'View-Transport-Orders', 'name' => 'View Transport Orders'],
            ['slug' => 'Create-Transport-Orders', 'name' => 'Create Transport Orders'],
            ['slug' => 'Edit-Transport-Orders', 'name' => 'Edit Transport Orders'],
            ['slug' => 'Delete-Transport-Orders', 'name' => 'Delete Transport Orders'],

            ['slug' => 'View-Vehicles', 'name' => 'View Vehicles'],
            ['slug' => 'Create-Vehicles', 'name' => 'Create Vehicles'],
            ['slug' => 'Edit-Vehicles', 'name' => 'Edit Vehicles'],
            ['slug' => 'Delete-Vehicles', 'name' => 'Delete Vehicles'],

            ['slug' => 'View-Drivers', 'name' => 'View Drivers'],
            ['slug' => 'Create-Drivers', 'name' => 'Create Drivers'],
            ['slug' => 'Edit-Drivers', 'name' => 'Edit Drivers'],
            ['slug' => 'Delete-Drivers', 'name' => 'Delete Drivers'],

            ['slug' => 'View-Escorts', 'name' => 'View Escorts'],
            ['slug' => 'Create-Escorts', 'name' => 'Create Escorts'],
            ['slug' => 'Edit-Escorts', 'name' => 'Edit Escorts'],
            ['slug' => 'Delete-Escorts', 'name' => 'Delete Escorts'],

            ['slug' => 'View-Hired-Vehicles', 'name' => 'View Hired Vehicles'],
            ['slug' => 'Create-Hired-Vehicles', 'name' => 'Create Hired Vehicles'],
            ['slug' => 'Edit-Hired-Vehicles', 'name' => 'Edit Hired Vehicles'],
            ['slug' => 'Delete-Hired-Vehicles', 'name' => 'Delete Hired Vehicles'],

            ['slug' => 'View-Fuel-Logs', 'name' => 'View Fuel Logs'],
            ['slug' => 'Create-Fuel-Logs', 'name' => 'Create Fuel Logs'],
            ['slug' => 'Edit-Fuel-Logs', 'name' => 'Edit Fuel Logs'],
            ['slug' => 'Delete-Fuel-Logs', 'name' => 'Delete Fuel Logs'],

            ['slug' => 'View-Maintenance-Logs', 'name' => 'View Maintenance Logs'],
            ['slug' => 'Create-Maintenance-Logs', 'name' => 'Create Maintenance Logs'],
            ['slug' => 'Edit-Maintenance-Logs', 'name' => 'Edit Maintenance Logs'],
            ['slug' => 'Delete-Maintenance-Logs', 'name' => 'Delete Maintenance Logs'],

            ['slug' => 'View-Transport-Costing', 'name' => 'View Transport Costing'],
            ['slug' => 'Edit-Transport-Costing', 'name' => 'Edit Transport Costing'],

            ['slug' => 'View-Transport-Profit-Analysis', 'name' => 'View Transport Profit Analysis'],
            ['slug' => 'Print-Transport-Profit-Analysis', 'name' => 'Print Transport Profit Analysis'],



            
        ];// ================== PERMISSIONS ==================
foreach ($permissions as $perm) {
    $existing = Permission::where('slug', $perm['slug'])->first();

    if ($existing) {
        $existing->name = $perm['name'];
        $existing->save();
    } else {
        Permission::create([
            'slug' => $perm['slug'],
            'name' => $perm['name']
        ]);
    }
}


// ================== ROLES ==================
$roles = [
    ['slug' => 'Admin', 'name' => 'Admin'],
    ['slug' => 'CEO', 'name' => 'CEO'],
    ['slug' => 'Managing Director (MD)', 'name' => 'Managing Director (MD)'],
    ['slug' => 'Accountant Director (DAF)', 'name' => 'Accountant Director (DAF)'],
    ['slug' => 'Chief Accountant', 'name' => 'Chief Accountant'],
    ['slug' => 'Company Manager', 'name' => 'Company Manager'],
    ['slug' => 'Unit Manager', 'name' => 'Unit Manager'],
    ['slug' => 'Verifier', 'name' => 'Verifier'],
    ['slug' => 'Approver', 'name' => 'Approver'],
    ['slug' => 'Cashier', 'name' => 'Cashier'],
    ['slug' => 'IT Manager', 'name' => 'IT Manager'],
    ['slug' => 'Requester', 'name' => 'Requester'],
];
foreach ($roles as $role) {
    $existing = Role::where('slug', $role['slug'])->first();

    if (!$existing) {
        Role::create([
            'name' => $role['name'],
            'slug' => $role['slug'],
            'Status' => 'Active'
        ]);
    }
}

$adminRole = Role::where('slug', 'Admin')->first();

if ($adminRole) {

    $permissions = Permission::all();

    foreach ($permissions as $permission) {

        DB::table('roles_permissions')->updateOrInsert([
            'role_id' => $adminRole->id,
            'permission_id' => $permission->id
        ]);
    }
}

$user = new User();
$user->phone_No='0700000000';
$user->role='Admin-Developer';
$user->image='1759770327.IMG_9042.png';
$user->st_sign='sign.png';
$user->gender="Male";
$user->username='Admin';
$user->name="Eng.Kivuyo";
$user->status='Active';
$user->email='info@admin.co.tz';
$user->password = bcrypt('123456');
$user->gross_salary = 0;
$user->company_id = 1;
$user->comp_unit_id = 1;
$user->work_point_id = 2;
$user->save();

$user = new User();
$user->phone_No='0757851332';
$user->role='Managing Director (MD)';
$user->image='';
$user->st_sign='';
$user->gender="Male";
$user->username='Barnabas';
$user->name="Barnabas Nibengo";
$user->status='Active';
$user->email='barnabasnibengo@gmail.com';
$user->password = bcrypt('123456');
$user->gross_salary =1500000;
$user->company_id = 1;
$user->comp_unit_id = 1;
$user->work_point_id = 2;
$user->save();

$user = new User();
$user->phone_No='0686803114';
$user->role='Accountant Director (DAF)';
$user->image='Nicas Pasport.jpeg';
$user->st_sign='Nicas Sign.png';
$user->gender="Male";
$user->username='Nicas';
$user->name="Nicas Nibengo";
$user->status='Active';
$user->email='user1@admin.co.tz';
$user->password = bcrypt('123456');
$user->gross_salary = 1000000;
$user->company_id = 1;
$user->comp_unit_id = 1;
$user->work_point_id = 2;
$user->save();

$user = new User();
$user->phone_No='0664777123';
$user->role='Chief Accountant';
$user->image='';
$user->st_sign='';
$user->gender="Male";
$user->username='Olare';
$user->name="Rodgers Olare";
$user->status='Active';
$user->email='rogerdhimb@gmail.com';
$user->password = bcrypt('654321');
$user->gross_salary = 3120000 ;
$user->company_id = 1;
$user->comp_unit_id = 1;
$user->work_point_id = 2;
$user->save();

$user = new User();
$user->phone_No='0788270635';
$user->role='Admin';
$user->image ='';
$user->st_sign='';
$user->gender="Male";
$user->username='Administrator';
$user->name="Boniface kanenje";
$user->status='Active';
$user->email='boniface.kanenje@mbogomining.co.tz';
$user->password = bcrypt('kanenje17@!');
$user->gross_salary = 577777.78;
$user->company_id = 1;
$user->comp_unit_id = 1;
$user->work_point_id = 2;
$user->save();


/*
|--------------------------------------------------------------------------
| PRODUCTION USER COMPANY ASSIGNMENT
|--------------------------------------------------------------------------
| CEO and Admin-Developer stay in Holding.
| All other users are assigned to Mbogo Mining.
|--------------------------------------------------------------------------
*/

$holdingCompany = DB::table('company_sites')
    ->where('company_code', 'NHL001')
    ->first();

$mbogoCompany = DB::table('company_sites')
    ->where('company_code', 'MGL001')
    ->first();

$holdingWorkPoint = $holdingCompany
    ? DB::table('work_points')
        ->where('company_id', $holdingCompany->id)
        ->where('status', 'Active')
        ->orderBy('id')
        ->first()
    : null;

$mbogoWorkPoint = $mbogoCompany
    ? DB::table('work_points')
        ->where('company_id', $mbogoCompany->id)
        ->where('status', 'Active')
        ->orderBy('id')
        ->first()
    : null;

if ($holdingCompany && $holdingWorkPoint) {
    DB::table('users')
        ->where(function ($q) {
            $q->where('role', 'CEO')
              ->orWhere('role', 'MD')
              ->orWhere('role', 'Admin-Developer')
              ->orWhere('username', 'Admin');
        })
        ->update([
            'company_id' => $holdingCompany->id,
            'comp_unit_id' => $holdingWorkPoint->comp_unit_id,
            'work_point_id' => $holdingWorkPoint->id,
            'updated_at' => now(),
        ]);
}

if ($mbogoCompany && $mbogoWorkPoint) {
    DB::table('users')
        ->where(function ($q) {
            $q->whereNull('role')
              ->orWhereNotIn('role', ['CEO','MD', 'Admin-Developer']);
        })
        ->where('username', '!=', 'Admin')
        ->update([
            'company_id' => $mbogoCompany->id,
            'comp_unit_id' => $mbogoWorkPoint->comp_unit_id,
            'work_point_id' => $mbogoWorkPoint->id,
            'updated_at' => now(),
        ]);
}

$this->command->info('Users assigned: CEO/Admin-Developer to Holding, all others to Mbogo Mining.');

}
}